


#keycloak:
#  clientid: fiona-rest-api




#keycloak:
#  auth-server-url: http://localhost:8181/auth/admin
#  realm: master
#  resource: admin-cli
#  bearer-only: true
#  public-client: true
#  credentials:
#    username: admin_user
#    password: admin_password


keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: test-realm
  resource: springboot-keycloak-client
  bearer-only: true
  public-client: true






