





server:
  port: 8021
#
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: master
  resource: admin-cli
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  public-client: true









