#keycloak:
#  auth-server-url: http://localhost:8181/auth/admin
#  realm: master
#  granttype: password
#  resource: fiona-rest-api
#  bearer-only: true
#  credentials:
#    secret: Goqc06CeM0BumU92R8c6wnw16D23uzI4
##    username: admin_user
##    password: admin_password
#  ssl-required: external
#  use-resource-role-mapping: true


#keycloak:
#  clientid: fiona-rest-api



server:
  port: 8080

spring:
  application:
    name: keycloak-spring-boot-project

keycloak:
  auth-server-url: http://localhost:8181/auth/admin
  realm: Master
  resource: client
  username: admin_user
  password: admin_password
  bearer-only: true



